# Generated by Django 5.1.2 on 2024-10-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="recipes_image/")),
                ("servings", models.PositiveIntegerField()),
                (
                    "prepration_time",
                    models.DurationField(help_text="Preparation time (hh:mm:ss)"),
                ),
                ("total_time", models.DurationField(help_text="Total time (hh:mm:ss)")),
                ("calories", models.PositiveIntegerField()),
                ("instructions", models.TextField()),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cuisine",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "South Indian"),
                            (2, "North Indian"),
                            (3, "Chinese"),
                        ]
                    ),
                ),
                (
                    "food_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Veg"), (2, "Non-Veg"), (3, "Vegan")]
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")]
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipes",
                    models.ManyToManyField(
                        related_name="collections", to="recipeApp.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.FloatField()),
                (
                    "unit",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "gms"),
                            (2, "number"),
                            (3, "tsp"),
                            (4, "tbsp"),
                            (5, "litres"),
                        ]
                    ),
                ),
                ("optional", models.BooleanField(default=False)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipeApp.recipe",
                    ),
                ),
            ],
        ),
    ]
