# Generated by Django 5.1.2 on 2024-10-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "gms"),
                    (2, "number"),
                    (3, "tsp"),
                    (4, "tbsp"),
                    (5, "litres"),
                    (6, "cup"),
                ]
            ),
        ),
    ]
